### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by axic** [wasmx/wasm-chisel#26]
The original proposal for CLI was only have a configuration format. 

This briefly described in the README: https://github.com/wasmx/wasm-chisel#configuration-file-wip

@jakelang has raised that it would make sense to have a stand alone tool too.

I think we could do something like this, in line with other tools:
- `chisel carve` (with `chisel run` for the old-school folks) which looks for a configuration file and executes it
- `chisel carve <module> {params} <filename>`

**Comment by axic** [comment]
Suggestion by @jakelang
- Maybe chisel validate?
- Or just drop subcommands completely and do chisel -m <module>, e.g chisel translate for translation etc

I think it makes sense following the internal abstraction and have `create` / `validate` / `translate`: `chisel create <module> {options}`

**Comment by jakelang** [comment]
Alternatively: `chisel` with no subcommand will search for a `chisel.yaml`, in the current dir, `$HOME`, and `$PATH` in that order.

`chisel` with a subcommand `validate | create | translate` and a module list will run specific modules of the kind on the provided binary.

**Comment by axic** [comment]
The agreement is:
- `chisel run` searches for `chisel.yml` / `chisel.toml` (need to decide)
- `chisel create`/etc. as in 
https://github.com/wasmx/wasm-chisel/issues/26#issuecomment-440062147

**Comment by jakelang** [comment]
@axic voting for YAML.

**Comment by axic** [comment]
I prefer yaml, but if toml is easier in Rust it is fine with me.
