### ISSUE TITLE
Translator for start function (remapstart)

### ISSUE THREAD

**Issue by axic** [wasmx/wasm-chisel#99]
1. Rename the function pointed to by the start section to `main`. If there is another function named `main`, rename it (prefix it with `_`) to avoid conflict – if there this conflicts with another function, keep adding underscore prefixes until it won't.

2. Remove the start section. (See `dropstartfunction`.)

**Comment by jwasinger** [comment]
Gonna take this one on

**Comment by jwasinger** [comment]
> (See dropstartfunction.)

What do you mean by this?

**Comment by axic** [comment]
> > (See dropstartfunction.)
>
> What do you mean by this? Referring to the pwasm API I am guessing.

https://github.com/wasmx/wasm-chisel/blob/master/libchisel/src/trimstartfunc.rs

**Comment by jakelang** [comment]
@axic I see no real reason to drop the names section, as export names are unique. The names section exists solely as a custom section to aid debuggers and other binary tools.

**Comment by axic** [comment]
The reason is that we were lazy to check if the exported names are duplicated in the names section.

**Comment by jakelang** [comment]
They aren't, and the names section doesn't seem to matter anyway. Maybe introducing another module for that later would make more sense (as opposed to implicit behavior in `remapstart`).

**Comment by axic** [comment]
We have another which removes sections. It does matter because we don't want to generate an invalid output.

This is the spec: https://webassembly.github.io/spec/core/appendix/custom.html#name-section

**Comment by axic** [comment]
Agreed that other transformations changing the export section don't deal with the names section. We should clarify this and fix if needed, but we can do it after remapstart.
